version: '3'
services:
  heartbeat:
    image: docker.elastic.co/beats/heartbeat:8.11.3
    user: heartbeat
    command:
      - heartbeat
      - -e
      - --strict.perms=false
    env_file:
      - .env
    environment:
      - HOSTNAME=${HOSTNAME}
    network_mode: "host"
    cap_add:
      - NET_RAW
    volumes:
      - ./configs/heartbeat.yml:/usr/share/heartbeat/heartbeat.yml:ro
    restart: always

  metricbeat:
    image: docker.elastic.co/beats/metricbeat:8.11.3
    privileged: true
    user: root
    command:
      - metricbeat
      - -e
      - -system.hostfs=/hostfs
    env_file:
      - .env
    network_mode: "host"
    volumes:
      - ./configs/metricbeat.yml:/usr/share/metricbeat/metricbeat.yml:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /sys/fs/cgroup:/hostfs/sys/fs/cgroup:ro
      - /proc:/hostfs/proc:ro
      - /var/run/dbus/system_bus_socket:/hostfs/var/run/dbus/system_bus_socket:ro
      - /:/hostfs:ro
    restart: always
