heartbeat.monitors:
- type: icmp
  id: ping-localhost
  name: '${HOSTNAME}'
  hosts: ["localhost"]
  schedule: '*/5 * * * * * *'

processors:
- add_host_metadata:
    cache.ttl: 5m

output.elasticsearch:
  hosts: '${ES_HOST}'
  username: '${ES_USER:}'
  password: '${ES_PASSWORD:}'
  ssl:
    verification_mode: "none"
