heartbeat.monitors:
- type: icmp
  id: ping-localhost
  name: Localhost Ping
  hosts: ["localhost"]
  schedule: '*/5 * * * * * *'

output.elasticsearch:
  hosts: '${ES_HOST}'
  username: '${ES_USER:}'
  password: '${ES_PASSWORD:}'
  ssl:
    verification_mode: "none"
